---
# install fits
- name: install zip utility
  sudo: yes
  apt: name=unzip state=present

- name: download fits zip version {{ fits_version }}
  become: yes
  get_url: url=http://projects.iq.harvard.edu/files/fits/files/fits-{{ fits_version }}.zip owner={{ install_user }} group={{ install_group }} dest={{ install_path }}/fits-{{ fits_version }}.zip

- name: unpack fits
  become: yes
  unarchive: src={{ install_path }}/fits-{{ fits_version }}.zip dest={{ install_path }}/ creates={{ install_path }}/fits-{{ fits_version }}/fits.sh copy=no

- name: make fits executable
  become: yes
  file: path={{ install_path }}/fits-{{ fits_version }}/fits.sh mode=0755

- name: copy fits scripts
  sudo: yes
  shell: cp -r {{ install_path }}/fits-{{ fits_version }}/* /usr/local/bin/

- name: symlink fits alias
  sudo: yes
  file: src=/usr/local/bin/fits.sh dest=/usr/local/bin/fits state=link
  

