---
# installs database, dev library, and python psql adapter
- name: install postgresql packages
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
  - postgresql
  - libpq-dev
  - python-psycopg2
  notify:
  - set postgres password
  - configure md5 security
  - restart postgres server
  - create pg hydra database
  - add pg hydra user

- name: create pg_backups directory
  sudo: yes
  file: owner=postgres group=postgres state=directory path=/opt/pg_backups

- name: add pg_backups script
  sudo: yes
  template: src=pg_backups.j2 dest=/opt/pg_backups/pg_daily_double owner=root group=root mode=0755

- name: add pg_backups cron job
  sudo: yes
  cron: name="backup pg db" user=postgres job="/opt/pg_backups/pg_daily_double" minute="0" hour="1" state=present

- meta: flush_handlers
