---
# roles/hydra-stack/install/defaults/main.yml
install_path: /opt/install
# to run successfully with Java 8, you must run the openjdk1_8 role BEFORE the hydra-stock role
# so the openjdk1_8 role can overwrite this default:
java_home: /usr/lib/jvm/java-7-openjdk-amd64
# tomcat PermGen memory (for loading java classes, etc.)
tomcat_permgen_memory: 128M
# tomcat min memory allocation
tomcat_min_memory: 512m
# tomcat max memory allocation
tomcat_max_memory: 4096m
##tomcat_config_path: /etc/tomcat7/Catalina/localhost
##project_name: sufia-project
app_root: /opt/{{ project_name }}/current
fedora_config_file: /etc/default/tomcat7
# for CentOS, use /etc/tomcat/conf.d/fedora.conf
fedora_version: 4.7.1
#fedora_database only used in Fedora versions >= 4.6.0
fedora_database: file-simple
# for fcrepo 4.6.x, use minimal-default
fcdb_user: admin
fcdb_pass: admin123
fcdb_port: 5432
#need to change
servlet: tomcat7
# for CentOS, use tomcat
servlet_path: /var/lib/{{ servlet }}
tomcat_port: 8080
