---
# Apache configuration; splitting this out makes it easier to use for adjusting ssl certs when needed
- name: create apache vhosts file
  template: src=apache_config.j2 dest=/etc/apache2/sites-available/{{ project_name }}.conf owner=root group=root backup=no

- name: remove default apache site
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: symlink apache config
  file: src=/etc/apache2/sites-available/{{ project_name }}.conf dest=/etc/apache2/sites-enabled/{{ project_name }}.conf state=link

- name: enable ssl module
  command: a2enmod ssl
