---
# host group must be specified at command line, e.g.
# ansible-playbook configure.yml -e hosts=ec2hosts
# TODO: it should work to default to all ec2hosts in this way:
#   hosts: ec2hosts,&{{ hosts | default("all") }}
#   But I couldn't get this to work for me.
- name: configuration
  hosts: "{{ hosts }}"
  user: ubuntu
  gather_facts: true
  roles:
    - { role: packages, sudo: yes }
    - { role: set_timezone, sudo: yes }
    - { role: system_setup, sudo: yes }
    - { role: capistrano_setup, sudo: yes }
    - { role: ruby }
    - { role: hydra-stack/install }
    - { role: hydra-stack/config-capistrano }
    - { role: services }
    - { role: apache-passenger, sudo: yes }
    - { role: app-config, sudo: yes }
