---
# ROLE: packages
# roles/packages/tasks/main.yml
#
# updates apt, installs packages used by other installation/configuration tasks
#
- name: update apt cache
  become: yes
  apt: update_cache=yes

- name: install aptitude
  # on Debian Jessie aptitude is not installed by default, without it apt-get upgrade fails
  become: yes
  apt: name=aptitude state=installed

- name: upgrade apt packages
  become: yes
  apt: upgrade=full

- name: install dev tools and libraries
  become: yes
  apt: name={{ item }} state=latest
  with_items:
    - build-essential
    - git
    - git-core
    - curl
    - openssl
    - libreadline6
    - libreadline6-dev
    - zlib1g
    - zlib1g-dev
    - libssl-dev
    - libyaml-dev
    - libxml2-dev
    - libxslt-dev
    - autoconf
    - libc6-dev
    - ncurses-dev
    - automake
    - libtool
    - bison
    - subversion
    - pkg-config
    - libmagickwand-dev
    - imagemagick
    - libcurl4-openssl-dev
    - libxvidcore-dev
    - redis-server
    - xfsprogs
    - libsqlite3-dev
    - libreoffice
