---
- name: create shared initializers
  template: src={{ item }}.j2 dest={{ shared_root }}/config/initializers/{{ item }} owner={{ capistrano_user }} group={{ capistrano_group }} backup=no
  with_items:
      - blacklight_initializer.rb
      - devise.rb
