---
- name: disable SELinux
  become: yes
  selinux: conf=/etc/selinux/config state=disabled
  when: ansible_distribution == "CentOS"

- name: update ssh config
  become: yes
  template: src=ssh_config dest=/etc/ssh/sshd_config backup=yes
  notify:
  - restart ssh service

- meta: flush_handlers

- name: add log rotation for production logs
  become: yes
  template: src=logrotate-rails.j2 dest=/etc/logrotate.d/rails
    
- name: add log rotation for catalina.out (tomcat/fedora/solr logs)
  become: yes
  template: src=logrotate-tomcat dest=/etc/logrotate.d/tomcat7 backup=yes
