---
# roles/imagemagick/defaults/main.yml 
install_path: /opt/install
magick_path: "{{ install_path }}/imagemagick_sources" # needs double-quotes for yaml syntax
openjpg_ver: '2.1.0'
libtiff_ver: '4.0.5'
libpng_ver: '1.6.20'
imagemagick_ver: '.' # call the role with imagemagick_ver: '6.8' to get the most recent 6.8 release, '.' to match the newest release 
