---
- name: set fedora version if absent
  set_fact: fedora_version="4.1.0"
  when: fedora_version is undefined
  
- name: fedora version to install {{ fedora_version | default("4.1.0") }}  
  # Handy in cases where we're logging or watching the console
  debug: msg="Set 'fedora_version' in your variables to install a different version of Fedora Commons"
  
- name: download fedora
  become: yes
  get_url: url=http://repo1.maven.org/maven2/org/fcrepo/fcrepo-webapp/{{ fedora_version }}/fcrepo-webapp-{{ fedora_version }}.war owner={{ install_user }} group={{ install_group }} dest={{ install_path }}/fcrepo-webapp-{{ fedora_version }}.war timeout=100

- name: make fedora data dir
  file: owner=tomcat7 group=tomcat7 state=directory path=/opt/fedora-data
  become: yes

- name: check fedora.war
  become: yes
  stat: path=/var/lib/tomcat7/webapps/fedora.war
  register: fedora_war

- name: copy over fedora.war
  become: yes
  command: cp {{ install_path }}/fcrepo-webapp-{{ fedora_version }}.war /var/lib/tomcat7/webapps/fedora.war
  when: fedora_war.stat.exists == False

- name: create tomcat config and java options
  become: yes
  template: src=tomcat7.j2 dest=/etc/default/tomcat7 backup=yes
# TODO: make Java options configurable at the time of the ansible run

# TODO: make this a service called from main.yml
- name: restart tomcat
  become: yes
  service: name=tomcat7 enabled=yes state=restarted
