---
  # This role only works on Ubuntu/Debian
  # if you are building a CentOS 7 box, use Solr 5.x
- name: create velocity log
  become: yes
  file: path=/var/log/tomcat7/velocity.log state=touch owner=tomcat7 group=tomcat7 mode=0644

- name: symlink velocity log
  become: yes
  file: src=/var/log/tomcat7/velocity.log dest=/var/lib/tomcat7/velocity.log state=link

- name: download solr tarball
  become: yes
  get_url: url=http://archive.apache.org/dist/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz dest={{ install_path }}/solr-{{ solr_version }}.tgz force=no
  # when we upgrade to ansible 2.0, add checksum="md5:{{ solr_md5 }}" 

- name: untar solr tarball
  become: yes
  unarchive: src={{ install_path }}/solr-{{ solr_version }}.tgz dest={{ install_path }}/ creates={{ install_path }}/solr-{{ solr_version }}/bin/solr copy=no

- name: check solr dir
  become: yes
  stat: path=/opt/solr/lib
  register: solr_dir

- name: make solr lib dir
  file: owner=tomcat7 group=tomcat7 state=directory path=/opt/solr/lib
  become: yes
  when: solr_dir.stat.exists == False

- name: copy over war file
  become: yes
  command: cp {{ install_path }}/solr-{{ solr_version }}/dist/solr-{{ solr_version }}.war /opt/solr/

- name: copy over dist jars
  become: yes
  shell: cp {{ install_path }}/solr-{{ solr_version }}/dist/*.jar /opt/solr/lib/

- name: copy over contrib dir
  become: yes
  command: cp -r {{ install_path }}/solr-{{ solr_version }}/contrib /opt/solr/lib/

- name: copy over example collection
  become: yes
  command: cp -r --remove-destination {{ install_path }}/solr-{{ solr_version }}/example/solr/collection1 /opt/solr/

- name: copy logging jars
  become: yes
  shell: cp {{ install_path }}/solr-{{ solr_version }}/example/lib/ext/*.jar /usr/share/tomcat7/lib/

- name: set ownership and group for solr
  become: yes
  shell: chown -R tomcat7:tomcat7 /opt/solr

- name: copy log4j properties file
  become: yes
  shell: cp {{ install_path }}/solr-{{ solr_version }}/example/resources/log4j.properties /usr/share/tomcat7/

- name: set ownership and group for tomcat
  become: yes
  shell: chown -R tomcat7:tomcat7 /usr/share/tomcat7

- name: create solr context file
  become: yes
  template: src=hydra_xml.j2 dest=/opt/solr/{{ solr_context }}.xml group=tomcat7 owner=tomcat7

- name: symlink solr context file to tomcat
  become: yes
  file: src=/opt/solr/{{ solr_context }}.xml dest={{ tomcat_config_path }}/{{ solr_context }}.xml state=link

- name: symlink schema from code to solr
  become: yes
  file: src={{ app_root }}/solr_conf/conf/schema.xml dest=/opt/solr/collection1/conf/schema.xml state=link force=yes

- name: symlink solrconfig from code to solr
  become: yes
  file: src={{ app_root }}/solr_conf/conf/solrconfig.xml dest=/opt/solr/collection1/conf/solrconfig.xml state=link force=yes

- name: set the solr port
  set_fact:
    solr_port: 8080
