---
- name: create velocity log
  sudo: yes
  file: path=/var/log/tomcat7/velocity.log state=touch owner=tomcat7 group=tomcat7 mode=0644

- name: symlink velocity log
  sudo: yes
  file: src=/var/log/tomcat7/velocity.log dest=/var/lib/tomcat7/velocity.log state=link

- name: check solr file
  sudo: no
  stat: path={{ install_path }}/solr-4.10.3.tgz
  register: solr_tarball

- name: download solr tarball
  get_url: url=http://archive.apache.org/dist/lucene/solr/4.10.3/solr-4.10.3.tgz dest={{ install_path }}/
  when: solr_tarball.stat.exists == False

- name: untar solr tarball
  unarchive: src={{ install_path }}/solr-4.10.3.tgz dest=/opt/install/ copy=no

- name: check solr dir
  sudo: no
  stat: path=/opt/solr/lib
  register: solr_dir

- name: make solr lib dir
  file: owner=tomcat7 group=tomcat7 state=directory path=/opt/solr/lib
  sudo: yes
  when: solr_dir.stat.exists == False

- name: copy over war file
  sudo: yes
  command: cp {{ install_path }}/solr-4.10.3/dist/solr-4.10.3.war /opt/solr/

- name: copy over dist jars
  sudo: yes
  shell: cp {{ install_path }}/solr-4.10.3/dist/*.jar /opt/solr/lib/

- name: copy over contrib dir
  sudo: yes
  command: cp -r {{ install_path }}/solr-4.10.3/contrib /opt/solr/lib/

- name: copy over example collection
  sudo: yes
  command: cp -r {{ install_path }}/solr-4.10.3/example/solr/collection1 /opt/solr/

- name: copy logging jars
  sudo: yes
  shell: cp {{ install_path }}/solr-4.10.3/example/lib/ext/*.jar /usr/share/tomcat7/lib/

- name: set ownership and group for solr
  sudo: yes
  shell: chown -R tomcat7:tomcat7 /opt/solr

- name: copy log4j properties file
  sudo: yes
  shell: cp {{ install_path }}/solr-4.10.3/example/resources/log4j.properties /usr/share/tomcat7/

- name: set ownership and group for tomcat
  sudo: yes
  shell: chown -R tomcat7:tomcat7 /usr/share/tomcat7

- name: create solr xml file
  sudo: yes
  template: src=hydra_xml.j2 dest=/opt/solr/hydra.xml group=tomcat7 owner=tomcat7

- name: symlink solr xml file to tomcat
  sudo: yes
  file: src=/opt/solr/hydra.xml dest=/etc/tomcat7/Catalina/localhost/hydra.xml state=link

- name: restart tomcat
  sudo: yes
  service: name=tomcat7 enabled=yes state=restarted
  
