---
# adapted from
# https://github.com/akishin/ansible-playbooks/blob/master/lokka/roles/passenger/tasks/main.yml

- name: install passenger gem
  gem: name=passenger user_install=no state=present version={{ passenger_ver }}

- name: install apache packages
  apt: name={{ item }} state=present
  with_items:
    - apache2-prefork-dev
    - apache2-mpm-worker

- name: install passenger-install-apache2-module
  become: yes
  shell: passenger-install-apache2-module --auto creates=/usr/local/lib/ruby/gems/{{ ruby_ver }}/gems/passenger-{{ passenger_ver }}/buildout/apache2/mod_passenger.so

- name: generate passenger.conf file
  shell: passenger-install-apache2-module --snippet > /etc/apache2/conf-available/passenger.conf creates=/etc/apache2/conf-available/passenger.conf

- name: symlink passenger config
  file: src=/etc/apache2/conf-available/passenger.conf path=/etc/apache2/conf-enabled/passenger.conf state=link
  become: yes
