---
- name: install zip utility
  sudo: yes
  apt: name=unzip state=present

- name: download fits zip
  become: yes
  get_url: url=http://projects.iq.harvard.edu/files/fits/files/fits-0.8.4.zip owner={{ install_user }} group={{ install_group }} dest={{ install_path }}/fits-0.8.4.zip
  
- name: unpack fits
  become: yes
  unarchive: src={{ install_path }}/fits-0.8.4.zip dest={{ install_path }}/ creates={{ install_path }}/fits-0.8.4/fits.sh copy=no

- name: make fits executable
  become: yes
  file: path={{ install_path }}/fits-0.8.4/fits.sh mode=0755

- name: copy fits
  sudo: yes
  shell: cp -r {{ install_path }}/fits-0.8.4/* /usr/local/bin/

- name: symlink fits
  sudo: yes
  file: src=/usr/local/bin//fits.sh dest=/usr/local/bin/fits state=link

