---
- name: check for local libpng
  local_action: stat path="{{ local_magick_path }}/libpng-{{ libpng_ver }}.tar.gz"
  register: libpng

- name: copy libpng source
  copy: 
    src: "{{ local_magick_path }}/libpng-{{ libpng_ver }}.tar.gz"
    dest: "{{ magick_path }}/libpng-{{ libpng_ver }}.tar.gz"
  when: 
    - libpng.stat.exists == True

- name: download libpng source
  get_url: 
    url: http://downloads.sourceforge.net/project/libpng/libpng16/{{ libpng_ver }}/libpng-{{ libpng_ver }}.tar.gz 
    dest: "{{ magick_path }}/libpng-{{ libpng_ver }}.tar.gz"
    force: no

- name: unzip libpng source
  unarchive: src={{ magick_path }}/libpng-{{ libpng_ver }}.tar.gz dest={{ magick_path }}/ creates={{ magick_path }}/libpng-{{ libpng_ver }} copy=no

- name: configure libpng
  shell: cd {{ magick_path }}/libpng-{{ libpng_ver }} && ./configure

- name: make libpng
  shell: cd {{ magick_path }}/libpng-{{ libpng_ver }} && make 

- name: install libpng
  become: yes
  shell: cd {{ magick_path }}/libpng-{{ libpng_ver }} && make install
