---
- name: check for local libtiff
  local_action: stat path="{{ local_magick }}/tiff-{{ libtiff_ver }}.tar.gz"
  register: libtiff

- name: copy libtiff source
  copy: 
    src: "{{ local_magick }}/tiff-{{ libtiff_ver }}.tar.gz"
    dest: "{{ magick_path }}/tiff-{{ libtiff_ver }}.tar.gz"
  when:
    - libtiff.stat.exists == True

- name: download libtiff source
  get_url: 
    url: http://download.osgeo.org/libtiff/tiff-{{ libtiff_ver }}.tar.gz 
    dest: "{{ magick_path }}/tiff-{{ libtiff_ver }}.tar.gz"
    force: no

- name: unzip libtiff source
  unarchive: src={{ magick_path }}/tiff-{{ libtiff_ver }}.tar.gz dest={{ magick_path }}/ creates={{ magick_path }}/tiff-{{ libtiff_ver }} copy=no

- name: configure libtiff
  shell: cd {{ magick_path }}/tiff-{{ libtiff_ver }} && ./configure

- name: make libtiff
  shell: cd {{ magick_path }}/tiff-{{ libtiff_ver }} && make 

- name: install libtiff
  become: yes
  shell: cd {{ magick_path }}/tiff-{{ libtiff_ver }} && make install
