---
  # standalone solr requires java 8
  # until java 8 becomes the default package for apt,
  # you must include the openjdk1_8 role on Ubuntu/Debian before the hydra-stack role when installing solr >=5.x

- name: download solr checksum
  become: yes
  get_url: url=http://archive.apache.org/dist/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz.md5 dest={{ install_path }}/solr-{{ solr_version }}.tgz.md5 force=no

- name: read solr checksum
  become: yes
  shell: awk '{print $1}' {{ install_path }}/solr-{{ solr_version }}.tgz.md5
  register: solr_md5

- name: download solr tarball
  become: yes
  get_url: url=http://archive.apache.org/dist/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz dest={{ install_path }}/solr-{{ solr_version }}.tgz force=no checksum="md5:{{ solr_md5.stdout }}" 

- name: untar solr tarball
  become: yes
  unarchive: src={{ install_path }}/solr-{{ solr_version }}.tgz dest={{ install_path }}/ creates={{ install_path }}/solr-{{ solr_version }}/bin/solr copy=no

- name: check if standalone solr is installed
  stat: path=/etc/default/solr.in.sh
  register: solr_init_script

- name: run standalone solr service script
  when: solr_init_script.stat.exists == False
  become: yes
  shell: bash {{ install_path }}/solr-{{ solr_version }}/bin/install_solr_service.sh {{ install_path }}/solr-{{ solr_version }}.tgz -p {{ solr_port }}

- name: create default collection
  become: yes
  become_user: solr
  shell: /opt/solr/bin/solr create -c {{ solr_core }} -d basic_configs -p {{ solr_port }} creates=/var/solr/data/{{ solr_core }}

- name: symlink schema from code to solr
  become: yes
  file: src={{ app_root }}/solr/config/schema.xml dest=/var/solr/data/{{ solr_core }}/conf/schema.xml state=link force=yes

- name: symlink solrconfig from code to solr
  become: yes
  file: src={{ app_root }}/solr/config/solrconfig.xml dest=/var/solr/data/{{ solr_core }}/conf/solrconfig.xml state=link force=yes

- name: Set JVM heap size
  become: yes
  lineinfile:
    path: /etc/default/solr.in.sh
    state: present
    regexp: '^#SOLR_JAVA_MEM|^SOLR_JAVA_MEM'
    line: SOLR_JAVA_MEM="-Xms{{ solr_min_mem }}m -Xmx{{ solr_max_mem }}m"

- name: set solr to restart on reboot
  become: yes
  service: name=solr enabled=yes
  when: ansible_distribution == "CentOS"

# Workaround for bug https://github.com/ansible/ansible-modules-core/issues/915.
- name: Ensure solr is stopped (RHEL 7 workaround)
  become: yes
  command: service solr stop
  when: (ansible_distribution == "CentOS") and (solr_init_script.stat.exists == False)
