---
# roles/shibd/defaults/main.yml
apache: apache2
# use httpd for CentOS 7
callback_url: /users/auth/shibboleth/callback
idp_discovery_url: https://{{ idp_url }}/DS/WAYF
idp_entity_id: https://{{ idp_url }}/idp/shibboleth
idp_url: shibboleth.curationexperts.com
shibboleth_attributes:
  - { saml2_attribute_name: "urn:oid:2.16.840.1.113730.3.1.241", saml2_attribute_id: "displayName"}
  - { saml2_attribute_name: "urn:oid:0.9.2342.19200300.100.1.1", saml2_attribute_id: "uid"}
sp_entity_id: https://{{ server_name }}/shibboleth
sp_remote_user: uid
